# Generated by Django 6.0.1 on 2026-01-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='participant',
            name='expected_price',
            field=models.IntegerField(blank=True, help_text='만원 단위', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='product',
            field=models.CharField(blank=True, choices=[('sneakers', '한정판 스니커즈'), ('concert', '콘서트/공연 티켓'), ('game', '한정판 게임/피규어')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='exp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='loss',
            field=models.IntegerField(blank=True, help_text='1=손실회피 강함, 7=약함', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='risk',
            field=models.IntegerField(blank=True, help_text='1=위험회피, 7=위험선호', null=True),
        ),
        migrations.AlterModelTable(
            name='participant',
            table='participants',
        ),
    ]
