# Generated by Django 6.0.1 on 2026-01-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_participant_options_participant_expected_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='risk',
            field=models.IntegerField(blank=True, help_text='1=복권A(안전), 2=복권B(중립), 3=복권C(위험)', null=True),
        ),
    ]
