# Generated by Django 6.0.1 on 2026-01-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participant_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='loss',
            field=models.IntegerField(blank=True, help_text='1=손실회피 강함(상황A), 2=손실회피 약함(상황B)', null=True),
        ),
    ]
