# Generated by Django 6.0.1 on 2026-02-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_alter_participant_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='나이'),
        ),
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호'),
        ),
    ]
