# Generated by Django 6.0.1 on 2026-02-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_participant_age_participant_name_participant_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='expected_price',
        ),
        migrations.AlterField(
            model_name='participant',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='구매 희망 상품'),
        ),
    ]
