# Generated by Django 6.0.1 on 2026-02-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_remove_participant_expected_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='participant',
            name='lottery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='risk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
