# Generated by Django 6.0.1 on 2026-03-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_remove_participant_loss_remove_participant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='lottery',
        ),
        migrations.AddField(
            model_name='participant',
            name='lottery_step1',
            field=models.IntegerField(blank=True, null=True, verbose_name='위험성향_중간지점'),
        ),
        migrations.AddField(
            model_name='participant',
            name='lottery_step2',
            field=models.IntegerField(blank=True, null=True, verbose_name='위험성향_상위구간'),
        ),
        migrations.AddField(
            model_name='participant',
            name='lottery_step3',
            field=models.IntegerField(blank=True, null=True, verbose_name='위험성향_하위구간'),
        ),
    ]
